/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package laboratorio7;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JComboBox;

/**
 *
 * @author Diego Carcamo
 */
public class Simulacion extends javax.swing.JPanel {

    /**
     * Creates new form Simulacion
     */
    
    ArrayList<Equipo> Equipos;
    public Simulacion(ArrayList<Equipo>Equipos) {
        
        this.Equipos= Equipos;
        
        
        
        
        initComponents();
    }

    public JComboBox<Equipo> getBox1() {
        return Box1;
    }

    public JComboBox<Equipo> getBox2() {
        return Box2;
    }
    
    
    
    
    
    //Funcion de simular
    public void simular(Equipo e1, Equipo e2){
        
        Random rand= new Random();
        
        int GolesE1= rand.nextInt(3);
        
        int GolesE2= rand.nextInt(3);
        
        
        Resultado1.setText(GolesE1+"");
        Resultado2.setText(GolesE2+"");
        
        
        e1.setPartJ(e1.getPartJ()+1);
        e1.setGolesF(e1.getGolesF()+GolesE1);
        e1.setGolesC(e1.getGolesC()+GolesE2);
        
        
        
        
        e2.setPartJ(e2.getPartJ()+1);
        e2.setGolesF(e2.getGolesF()+GolesE2);
         e2.setGolesC(e2.getGolesC()+GolesE1);
         
        
         
         if(GolesE1>GolesE2){
             e1.setPartG(e1.getPartG()+1);
             e2.setPartP(e2.getPartP()+1);
             e1.setPuntos(e1.getPuntos()+3);
             
             
             System.out.println(e1+" gano");
             
             
         
         
         }else if(GolesE1==GolesE2){
            e1.setPartE(e1.getPartE()+1);
             e2.setPartE(e2.getPartE()+1);
             e1.setPuntos(e1.getPuntos()+1);
              e2.setPuntos(e2.getPuntos()+1);
              
              System.out.println("Empate");
             
             
             
             
        
        }else{
             System.out.println(e2 +" Gano");
               e2.setPartG(e2.getPartG()+1);
                e1.setPartP(e1.getPartP()+1);
                  e2.setPuntos(e2.getPuntos()+3);
               
         
         
         
         
         }
         
         
        
        
         
         
        
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
        
        
    
    
    
    
    
    
    
    
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Box1 = new javax.swing.JComboBox<>();
        Box2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Resultado2 = new javax.swing.JLabel();
        Resultado1 = new javax.swing.JLabel();

        jLabel1.setText("Equipo 1");

        jLabel2.setText("Equipo 2");

        jButton1.setText("Simular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Resultado2.setBackground(new java.awt.Color(102, 102, 102));
        Resultado2.setText("-");

        Resultado1.setBackground(new java.awt.Color(153, 153, 153));
        Resultado1.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(Resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Equipo e1=(Equipo) Box1.getSelectedItem();
        
        Equipo e2= (Equipo) Box2.getSelectedItem();
        
        
        if(!e1.equals(e2)){
            
           simular(e1, e2);
        
        
        }
     
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Equipo> Box1;
    private javax.swing.JComboBox<Equipo> Box2;
    private javax.swing.JLabel Resultado1;
    private javax.swing.JLabel Resultado2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
